spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password: 
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  cloud:
    config:
      uri: http://localhost:8080

management.endpoints.web.exposure.include: prometheus,health
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true

springdoc:
  swagger-ui:
    enable: true